### ISSUE TITLE
Power + Cadence (maybe speed?) for Garmin

### ISSUE THREAD

**Issue by justinaugust** [intelligenate/dfc#16]
Hi-
I would love a firmware that has Power + Cadence (maybe speed?) for Garmin head units. 130 plus here. 

Forerunner 245 would be tight but know it's a bit more.

**Comment by veneman** [comment]
DFC should work with all Garmin head units from *30 onward. We've done extensive testing with the 130 and it works great. We haven't tested the 130 plus but expect it should work. Does the 130 plus not work for you? 

Unfortunately it won't work with the FR 245 since those don't support power meters. 

See the [compatibility table](https://github.com/intelligenate/dfc/blob/main/docs/user-guide.md#compatibility-tables) for a listing of what's known to work or not.
