### ISSUE TITLE
DFC not transmitting data anymore to Garmin Epix 2

### ISSUE THREAD

**Issue by Alexalas84** [intelligenate/dfc#25]
DFC is not transmitting any cadence or power data to Garmin Epix 2. This started happening a couple of months ago.

**Comment by veneman** [comment]
A beta update for certain Garmin devices (Epix (gen 2), Fenix 7, FR265,
and possibly others) was causing DFC to continually reset. The issue was
related to a parameter request from those devices for something that’s
not supported by DFC. DFC now ignores that type of request if it’s not
valid. 

The updated firmware is here
<https://github.com/intelligenate/dfc/releases/tag/power-cadence-
beta.4>. See the Firmware Updates
<https://github.com/intelligenate/dfc/blob/main/docs/user-
guide.md#firmware-updates> section in the User Guide
<https://github.com/intelligenate/dfc/blob/main/docs/user-guide.md> for
details on updating. Many other users have tested it and reported that
the fix works great for them and they're back in business.

On May 17, 2024, GitHub ***@***.***> wrote:
> DFC is not transmitting any cadence or power data to Garmin Epix 2.
> This started happening a couple of months ago.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/intelligenate/dfc/issues/25>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABPRUHLLBNEWKBIK6HO63BDZC2E4FAVCNFSM6AAAAABH44Y756VHI2DSMVQWIX3LMV43ASLTON2WKOZSGMYDGNRXGM4DSMI>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>
